sudo: false
language: c
os:
  - osx
  - linux
compiler:
  - clang
  - gcc
#matrix:
#  allow_failures:
#    - env: MPI_IMPL=openmpi
env:
  - MPI_IMPL=mpich
  - MPI_IMPL=openmpi
before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT
  - sh ./travis/install-autotools.sh $TRAVIS_ROOT
install:
  - sh ./travis/install-mpi.sh $TRAVIS_ROOT $MPI_IMPL
script:
  - sh ./travis/build-run.sh $TRAVIS_ROOT $MPI_IMPL
after_failure:
- echo "Sad panda"
- find . -name config.log -exec grep -L "configure: exit 0" {} ";" | xargs cat
notifications:
  email:
    recipients:
    - jeff.science@gmail.com
    on_success:
    - change
    on_failure:
    - always
